# Generated by Django 4.2.3 on 2023-07-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_image_advertising_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertising',
        ),
    ]
