# Generated by Django 4.2.3 on 2023-07-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='last_neme',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
