# Generated by Django 4.2.3 on 2023-07-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_sneakers_last_neme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertising',
        ),
    ]
